apiVersion: apps/v1
kind: Deployment
metadata:
  name: busyness
spec:
  replicas: 1
  selector:
    matchLabels:
      app: busyness
  template:
    metadata:
      labels:
        app: busyness
    spec:
      containers:
      - image: okteto.dev/busyness:latest
        name: busyness
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "3104767d-ebb2-4b08-a997-621c580549cd"
        - name: Vless_Path
          value: "/vl555187"
        - name: Vmess_UUID
          value: "3104767d-ebb2-4b08-a997-621c580549cd"
        - name: Vmess_Path
          value: "/vm666163"
        - name: Share_Path
          value: "/v2link"
